### ISSUE TITLE
DataModelTrait null return value types

### ISSUE THREAD

**Issue by mholubowski** [10quality/wp-query-builder#11]
The DataModelTrait::find and DataModelTrait::find_where functions return null when they don't find a record. The return value in the docblock does not indicate the `null` possibility which breaks static analysis.

https://github.com/10quality/wp-query-builder/blob/v1.0/src/Traits/DataModelTrait.php#L26

```
  /**
     * Static constructor that finds recond in database
     * and fills model.
     * @since 1.0.0
     * 
     * @param mixed $id
     * 
     * @return \TenQuality\WP\Database\Abstracts\DataModel|null <-- should add this |null
     */
    public static function find( $id )
    {
        $model = new self( [], $id );
        return $model->load();
    }
....
```

**Comment by amostajo** [comment]
@mholubowski btw this is stated in the wiki:
https://github.com/10quality/wp-query-builder/wiki/Handling-A-Data-Model#find
