### ISSUE TITLE
Support update() and ability to batch updated multiple records.

### ISSUE THREAD

**Issue by amostajo** [10quality/wp-query-builder#15]
Support `update()` on query builder class.

On models allow for updates, like this:

```php
$books = Book::where(['id' => ['operator' => 'IN', 'value' => $ids]]);

foreach ($books as $book) {
    Book::update($book, ['status' => 'read']);
}
```

**Comment by mholubowski** [comment]
Thanks for taking a look at this, would be very useful.

**Comment by amostajo** [comment]
@mholubowski Update functionality has been included and can be utilized in the following case scenarios:

1. **Within an instantiated model**

https://github.com/10quality/wp-query-builder/wiki/Handling-A-Data-Model#update
This can be used as an alternative to `save()` to only update certain data:
```php
$books = Book::where( ['id' => $ids] );

foreach ( $books as $book ) {
   $book->update( ['status' => 'read'] );
}
```

2. **As the model's static method (mass update)**

https://github.com/10quality/wp-query-builder/wiki/Handling-A-Data-Model#update
Used to update multiple records as once:
```php
Book::update_all(
    ['status' => 'read'],
    ['id' => $ids]
);
```

3. **In query builder**

https://github.com/10quality/wp-query-builder/wiki/Query-Results#update
Using the query builder to build an update statement:
```php
$success = wp_query_builder()
    ->from( 'books' )
    ->set( ['status' => 'read'] )
    ->where( ['id' => $ids] )
    ->update();
```
