### ISSUE TITLE
How to get results from model builder ?

### ISSUE THREAD

**Issue by temuujina** [10quality/wp-query-builder#18]
[https://github.com/10quality/wp-query-builder/wiki/Handling-A-Data-Model#builder](url)

`$builder = MyModel::builder()->select( 'model_table.name' );`

What is .name ? How to use it ? Don't understand how to get results from model builder? Is there any tutorial ?

When I try to run this code, 
`$model = Manuscript::find_where( ['BookId' => '1'] ); `

there is an error and wordpress crashes. How to get results ?

**Comment by amostajo** [comment]
Make sure to follow the docs. As long as you follow the model specification, it should work:
```php
use TenQuality\WP\Database\Abstracts\DataModel;
use TenQuality\WP\Database\Traits\DataModelTrait;

class Manuscript extends DataModel
{
    use DataModelTrait;
    /**
     * Data table name in database (without prefix).
     * @var string
     */
    const TABLE = 'manuscript';
    /**
     * Data table name in database (without prefix).
     * @var string
     */
    protected $table = self::TABLE;
    /**
     * Primary key column name. Default ID
     * @var string
     */
    protected $primary_key = 'ID';
}
```
