### ISSUE TITLE
How to write where clause and SQL NULL value ?

### ISSUE THREAD

**Issue by temuujina** [10quality/wp-query-builder#20]
SQL NULL's special, and I have to do WHERE field IS NULL, as NULL cannot be equal to anything. How to write where clause?

```
$builder
            ->select( 'o.Order, o.CurrentType)
            ->from( 'order as `o`' )
            ->where( [
                'o.CurrentType' => [
                'operator' => 'IS NULL',
                'value'    => NULL,
                ],
            ->get();
```

**Comment by garretthyder** [comment]
Hi @temuujina from the looks of the test suite you just do an equals check;
https://github.com/10quality/wp-query-builder/blob/9b814bbf478d800269feb982e4063cd6a24ebef5/tests/cases/QueryBuilderStatementsTest.php#L111-L126

`->where([ 'test_field' => null ])`
