### ISSUE TITLE
Create table from model

### ISSUE THREAD

**Issue by last-core** [10quality/wp-query-builder#22]
Given a custom model like this: 
```
<?php

namespace MvcTodo\Models;

use TenQuality\WP\Database\Abstracts\DataModel;
use TenQuality\WP\Database\Traits\DataModelTrait;

class Todo extends DataModel
{
    use DataModelTrait;
    /**
     * Data table name in database (without prefix).
     * @var string
     */
    const TABLE = 'todos';
    /**
     * Data table name in database (without prefix).
     * @var string
     */
    protected $table = self::TABLE;
    /**
     * Primary key column name. Default ID
     * @var string
     */
    protected $primary_key = 'id';
    /**
     * Model properties, data column list.
     * @var string
     */
    protected $attributes = [
        'id',
        'name',
    ];
        protected function protected_properties()
    {
        // The following is the default array list
        return [$this->primary_key, 'created_at', 'updated_at'];
    }
}
```
is the table created on install or it needs special handling?

**Comment by garretthyder** [comment]
@last-core To my understanding,
A Model is an interface layer and expects the database table/columns to already exist. 
You'll want to SQL CREATE TABLE via your database before interfacing to it.
https://www.w3schools.com/sql/sql_create_table.asp

**Comment by amostajo** [comment]
The problem is that creating a table from a model in this case is not that simple as a database table requires each field to have data type definitions and other settings that differ from PHP. Same as the definition of constraints.

Probably a better approach would be to build a migration addon and functionality separate from this.
